---
title: "Homework #6"
author: "Lynn Chen"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(p8105.datasets)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 1: 

```{r load and clean the data}
birthweight = read_csv("./data/birthweight.csv")

## Clean the data 

birthweight = birthweight %>% 
  janitor::clean_names() %>% 
  mutate(
    babysex = factor(babysex, levels = c("1", "2")),
    babysex = fct_recode(babysex, "Female" = "2", "Male" = "1"),
    frace = factor(frace, 
                       levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9")),
    frace = fct_recode(frace, 
                       "White" = "1",
                       "Black" = "2",
                       "Asian" = "3",
                       "Puerto Rican" = "4", 
                       "Other" = "8",
                       "Unknown" = "9"),
    malform = factor(malform, labels = c("Absent", "Present")),
    mrace = factor(mrace,  c(1, 2, 3, 4, 8)),
    mrace = fct_recode(mrace, 
                       "White" = "1",
                       "Black" = "2",
                       "Asian" = "3",
                       "Puerto Rican" = "4", 
                       "Other" = "8"))

## check for missing values
apply(is.na(birthweight),2,sum)
```

There are no missing values in the data!! YAY!    
